**Block 1: Import libraries**

In [105]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from bs4 import BeautifulSoup
import requests

In [172]:
url='https://en.wikipedia.org/wiki/MonsterVerse' #assign the 
webdata=pd.read_html(url) #assign the data to webdata
full_data= webdata[3]
full_data1=full_data.drop(full_data.index[[5]],axis=0) #get rid of Humans, Humans, Humans
full_data1

              Character  ...                        Films
              Character  ...            Godzilla vs. Kong
               Monsters  ...                     Monsters
0              Godzilla  ...                          CGI
1                  MUTO  ...              Archive footage
2             King Kong  ...              Eric PeteyS[57]
3         King Ghidorah  ...              Archive footage
4                 Rodan  ...              Archive footage
6       Ishiro Serizawa  ...                          NaN
7       Vivienne Graham  ...                          NaN
8        William Stentz  ...                          NaN
9            Ford Brody  ...                          NaN
10           Elle Brody  ...                          NaN
11            Joe Brody  ...                          NaN
12         Sandra Brody  ...                          NaN
13       Houston Brooks  ...                          NaN
14        William Randa  ...  Pictured with archive audio
15         James Conrad  ...                          NaN
16          Hank Marlow  ...                          NaN
17         Mason Weaver  ...                          NaN
18      Preston Packard  ...                          NaN
19              San Lin  ...                          NaN
20         Mark Russell  ...                Kyle Chandler
21      Madison Russell  ...           Millie Bobby Brown
22         Emma Russell  ...                     Pictured
23  Ilene and Ling Chen  ...                          NaN
24         Rick Stanton  ...                          NaN
25          Sam Coleman  ...                          NaN
26           Alan Jonah  ...                          NaN
27         Diane Foster  ...                          NaN
28       Jackson Barnes  ...                          NaN
29          Nathan Lind  ...          Alexander Skarsgård
30        Ilene Andrews  ...                 Rebecca Hall
31                  Jia  ...                Kaylee Hottle
32         Bernie Hayes  ...            Brian Tyree Henry
33       Josh Valentine  ...              Julian Dennison
34       Walter Simmons  ...                Demián Bichir
35         Ren Serizawa  ...                   Shun Oguri
36         Maia Simmons  ...                Eiza González
37           Guillermin  ...                Lance Reddick

[37 rows x 5 columns]

In [168]:
webdata[3].head()

       Character  ...             Films
       Character  ... Godzilla vs. Kong
        Monsters  ...          Monsters
0       Godzilla  ...               CGI
1           MUTO  ...   Archive footage
2      King Kong  ...   Eric PeteyS[57]
3  King Ghidorah  ...   Archive footage
4          Rodan  ...   Archive footage

[5 rows x 5 columns]

In [169]:
print(type(full_data1))

<class 'pandas.core.frame.DataFrame'>

In [182]:
full_data1.index = full_data1['Character']
full_data1.head()

                      Character  ...             Films
                      Character  ... Godzilla vs. Kong
                       Monsters  ...          Monsters
(Godzilla,)            Godzilla  ...               CGI
(MUTO,)                    MUTO  ...   Archive footage
(King Kong,)          King Kong  ...   Eric PeteyS[57]
(King Ghidorah,)  King Ghidorah  ...   Archive footage
(Rodan,)                  Rodan  ...   Archive footage

[5 rows x 5 columns]

In [219]:
data=full_data1.set_axis(['Character', 'Godzilla', 'Kong:Skull Island', 'Godzilla:King of the Monsters', 'Godzilla vs. Kong'], axis=1, inplace=False)
data.head(7)

                      Character  ... Godzilla vs. Kong
(Godzilla,)            Godzilla  ...               CGI
(MUTO,)                    MUTO  ...   Archive footage
(King Kong,)          King Kong  ...   Eric PeteyS[57]
(King Ghidorah,)  King Ghidorah  ...   Archive footage
(Rodan,)                  Rodan  ...   Archive footage

[5 rows x 5 columns]

                          Character  ... Godzilla vs. Kong
(Godzilla,)                Godzilla  ...               CGI
(MUTO,)                        MUTO  ...   Archive footage
(King Kong,)              King Kong  ...   Eric PeteyS[57]
(King Ghidorah,)      King Ghidorah  ...   Archive footage
(Rodan,)                      Rodan  ...   Archive footage
(Ishiro Serizawa,)  Ishiro Serizawa  ...               NaN
(Vivienne Graham,)  Vivienne Graham  ...               NaN

[7 rows x 5 columns]

In [221]:
data.to_csv('godzilla_data.csv',sep=',')

In [213]:
data=full_data1.set_axis(['Character', 'Godzilla', 'Kong:Skull Island', 'Godzilla:King of the Monsters', 'Godzilla vs. Kong'], axis=1, inplace=False)
df=data.style.hide_index()
df

In [222]:
df.to_csv('godzilla_data.csv',sep=',')

AttributeError: ignored

In [214]:
type(df)

pandas.io.formats.style.Styler

In [152]:
type('Characters')

str

In [173]:
#data2=data.drop(["(Humans,)"],axis=0)
#data2 
#I tried to do a different methods but could not work, even though I was using the string as my index name